services:
  - type: web
    name: splat-issue-tracker
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python create_default_image.py
      python manage.py collectstatic --no-input
      python manage.py migrate --no-input
      python manage.py create_demo_users
      python manage.py populate_sample_data
    startCommand: gunicorn --config gunicorn-cfg.py core.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: splat-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.7"

databases:
  - name: splat-db
    plan: free
    databaseName: splat_db
    user: splat_user
